feat: allow overriding or modifying the queryString for websockets
fastify/fastify-http-proxy pull request #349
Opened 2024-04-19 16:50 UTC by ttshivers

Allow overriding or modifying the queryString when proxying websockets.

Fixes: #348

#### Checklist

- [ ] run `npm run test` and `npm run benchmark`
- [ ] tests and/or benchmarks are included
- [ ] documentation is changed or added
- [ ] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-11)
      and the [Code of conduct](https://github.com/fastify/.github/blob/master/CODE_OF_CONDUCT.md)

2024-04-20 16:23 UTC, mcollina requested changes
can you please add a test for the new types?

2024-04-20 19:21 UTC, ttshivers commented
> can you please add a test for the new types?

Added a test in a new commit. Is that what you were looking for?

2024-04-22 09:38 UTC, mcollina approved these changes
lgtm

2024-04-22 12:08 UTC, merged

2024-04-23 01:35 UTC, ttshivers commented
Could a release be made with this change?